import Head from "next/head";
import Link from "next/link";

import styles from "./index.module.css";
import { env } from "~/env";
import { Button, ButtonGroup, Card, Container, Heading } from "@chakra-ui/react";
import { useRouter } from "next/router";
import axios from "axios";



export default function Home() {

  const router = useRouter()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container  w={"sm"} mt={8}>
        <Button
              mb={2}
              alignSelf="start"
              colorPalette={"blue"}
              onClick={() => {
                router.push("/login")
              }}>Login
            </Button>
        <Card.Root p={4} width={500}>
          <Heading>Mis ventas </Heading>
          <ButtonGroup mt={8}>

            <Button
              colorPalette={"blue"}
              onClick={() => {
                router.push("/sales/new")
              }}>Nueva Venta
            </Button>

            <Button
              colorPalette={"purple"}
              onClick={() => {
                router.push("/clients")
              }}>Client
            </Button>
          </ButtonGroup>
        </Card.Root>

      </Container>
    </>
  );
}
